services:
  fastapi_app:
    build: .
    container_name: streamoid_fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
      - ./data:/app/data  # ✅ Mount your database directory
